apiVersion: v1
kind: Service
metadata:
  name: nodeport-1
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 8081  # Port on the pods
    nodePort: 30001   # Port accessible externally on each node
  selector:
    app: client-microservice-v1  # Select pods with this label
