apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-microservice-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-microservice-v1
  template:
    metadata:
      labels:
        app: client-microservice-v1
    spec:
      containers:
      - name: client-microservice-v1
        image: martinignacioriosc/thinka-crm:client-microservice
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: client-microservice-v1
spec:
  selector:
    app: client-microservice-v1
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
