apiVersion: v1
kind: Service
metadata:
  name: nodeport-3
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 8083  # Port on the pods
    nodePort: 30003   # Port accessible externally on each node
  selector:
    app: project-microservice-v1  # Select pods with this label
