apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-microservice-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-microservice-v1
  template:
    metadata:
      labels:
        app: project-microservice-v1
    spec:
      containers:
      - name: project-microservice-v1
        image: martinignacioriosc/thinka-crm:project-microservice
        ports:
        - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: project-microservice-v1
spec:
  selector:
    app: project-microservice-v1
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
