apiVersion: v1
kind: Service
metadata:
  name: nodeport-2
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 8082  # Port on the pods
    nodePort: 30002   # Port accessible externally on each node
  selector:
    app: sale-microservice-v1  # Select pods with this label
