spring:
    datasource:
        url: jdbc:mysql://mysql:3306/sale-db
        username: root
        password: root_password_123
    jpa:
        hibernate:
            ddl-auto: update
server:
    port : 8082
logging:
    level:
        org.springframework: ERROR
