spring:
    datasource:
        url: jdbc:mysql://mysql:3306/client-db
        username: root
        password: root_password_123
server:
    port : 8081
logging:
    level:
        org.springframework: ERROR
